# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            Hackerz World
tagline:          Our crime is that of curiosity
description:      "A community that has come together to maintain and develop hacker culture."


author:
  name:           Hackerz World
  url:            https://twitter.com/hackerzdotworld

paginate:         5
# paginate_path:    '/page:num'
                    # Or '/my-jekyll-site/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Custom vars

